//
//  CityDetailPresenter.swift
//  Weather VIPER Example
//
//  Created Egor Sakhabaev on 15.07.2018.
//  Copyright © 2018 Egor Sakhabaev. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//

import UIKit

class CityDetailPresenter {
    // MARK: - Properties
    weak private var view: CityDetailView?
    var interactor: CityDetailInteractorInput?
    private let router: CityDetailWireframeInterface
    private var weather: Weather
    
    // MARK: - Initialization and deinitialization
    init(interface: CityDetailView, interactor: CityDetailInteractorInput?, router: CityDetailWireframeInterface, weather: Weather) {
        self.view = interface
        self.interactor = interactor
        self.router = router
        self.weather = weather
    }
    
    // MARK: - Public methods
    func didSelectCloseButton() {
        router.navigate(to: .cities)
    }

}

// MARK: - CityDetailPresenterInterface -
extension CityDetailPresenter: CityDetailPresenterInterface {
    
    func viewDidLoad() {
        let weatherInfo: WeatherInfo = (weather.city, weather.precipitation.icon, String(weather.temperature), weather.wind.icon)
        view?.display(weatherInfo)
    }
}

// MARK: - CityDetailInteractorOutput -
extension CityDetailPresenter: CityDetailInteractorOutput {
    
}

