//
//  CityDetailProtocols.swift
//  Weather VIPER Example
//
//  Created Egor Sakhabaev on 15.07.2018.
//  Copyright © 2018 Egor Sakhabaev. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//

import Foundation
//MARK: Wireframe -
enum CityDetailNavigationOption {
        case cities
    //    case secondModule(someData)
}

protocol CityDetailWireframeInterface: class {
    func navigate(to option: CityDetailNavigationOption)
}

//MARK: Presenter -
protocol CityDetailPresenterInterface: class {

    var interactor: CityDetailInteractorInput? { get set }
    
    func viewDidLoad()
    func didSelectCloseButton()
}
extension CityDetailPresenterInterface {
    func viewDidLoad() {/*leaves this empty*/}
}

//MARK: Interactor -
protocol CityDetailInteractorOutput: class {

    /* Interactor -> Presenter */
}

protocol CityDetailInteractorInput: class {

    var presenter: CityDetailInteractorOutput?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol CityDetailView: class {

    var presenter: CityDetailPresenterInterface?  { get set }

    func display(_ weatherInfo: WeatherInfo)
    /* Presenter -> ViewController */
}
