//
//  CityDetailConfigurator.swift
//  Weather VIPER Example
//
//  Created Egor Sakhabaev on 15.07.2018.
//  Copyright © 2018 Egor Sakhabaev. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//

import UIKit

struct CityDetailConfigurator {

    static func createModule(with weather: Weather) -> UIViewController {
        var view: CityDetailViewController!

        let viewController = UIStoryboard.init(name: "CityDetail", bundle: Bundle.main).instantiateInitialViewController()
        if viewController == nil {
            fatalError("Seems there is no initial view controller in CityDetail.storyboard")
        }

        if viewController is UINavigationController {
            view = (viewController as! UINavigationController).viewControllers.first as! CityDetailViewController
        } else {
            view = viewController as! CityDetailViewController
        }

        let interactor = CityDetailInteractor()
        let router = CityDetailRouter()
        let presenter = CityDetailPresenter(interface: view, interactor: interactor, router: router, weather: weather)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return viewController!
    }
}
