//
//  CityDetailInteractor.swift
//  Weather VIPER Example
//
//  Created Egor Sakhabaev on 15.07.2018.
//  Copyright © 2018 Egor Sakhabaev. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//

import UIKit

class CityDetailInteractor: CityDetailInteractorInput {

    weak var presenter: CityDetailInteractorOutput?
}
