//
//  CitiesConfigurator.swift
//  Weather VIPER Example
//
//  Created Egor Sakhabaev on 13.07.2018.
//  Copyright © 2018 Egor Sakhabaev. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//

import UIKit

struct CitiesConfigurator {

	static func createModule() -> UIViewController {
        var view: CitiesViewController!

        let viewController = UIStoryboard.init(name: "Cities", bundle: Bundle.main).instantiateInitialViewController()
        if viewController == nil {
            fatalError("Seems there is no initial view controller in Cities.storyboard")
        }

        if viewController is UINavigationController {
            view = (viewController as! UINavigationController).viewControllers.first as! CitiesViewController
        } else {
            view = viewController as! CitiesViewController
        }

        let interactor = CitiesInteractor()
        let router = CitiesRouter()
        let presenter = CitiesPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return viewController!
    }
}
