//
//  CitiesRouter.swift
//  Weather VIPER Example
//
//  Created Egor Sakhabaev on 13.07.2018.
//  Copyright © 2018 Egor Sakhabaev. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//

import UIKit

class CitiesRouter {

    weak var viewController: UIViewController?
}

// MARK: - CitiesWireframeInterface -
extension CitiesRouter: CitiesWireframeInterface {
    
    func navigate(to option: CitiesNavigationOption) {
        var vc: UIViewController?
        switch option {
        case .cityDeail(let weather):
            vc = CityDetailConfigurator.createModule(with: weather)
        }
        if vc != nil {
            DispatchQueue.main.async {
                self.viewController?.present(vc!, animated: true)
            }
        }
    }
}
