//
//  CitiesInteractor.swift
//  Weather VIPER Example
//
//  Created Egor Sakhabaev on 13.07.2018.
//  Copyright © 2018 Egor Sakhabaev. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//

import UIKit

class CitiesInteractor: CitiesInteractorInput {
    // MARK: - Properties
    weak var presenter: CitiesInteractorOutput?
    
    // MARK: - CitiesInteractorInput -
    func fetchWeather(for cityName: String) {
        WeatherManager.getWeather(for: cityName)
            .done { (weather) in
                guard let weather = weather else {
                    let error = ResponseError.with(code: nil, message: AlertMsg.unknownError)
                    self.presenter?.fetchedWeather(with: error)
                    return
                }
                self.presenter?.fetchedWeather(with: weather)
            }
            .catch { (error) in
                self.presenter?.fetchedWeather(with: error)
            }
            .finally {
                self.presenter?.fetched()
        }
    }
}
